#!/usr/bin/env bash
# Script that configures a new Ubuntu machine and install nginx

sudo apt-get update
suod apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx restart
