#!/usr/bin/env bash
# Responses to SIGs to prevent kill

echo $$ > /var/run/myscript.pid
while true;
do
  echo "To infinity and beyond"
  trap 'echo "I hate the kill command"' SIGTERM
  trap 'echo "Y U no love me?!"' SIGINT
  trap '$(sudo rm -rf /var/run/myscript.pid); exit' SIGQUIT SIGTERM
done
