#!/usr/bin/env bash
# Reconfigure host file for localhost and facebook

cp /etc/hosts ~/hosts.new
echo "127.0.0.2	locahosts" > ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
